### ISSUE TITLE
Klipper reports: ERROR

### ISSUE THREAD

**Issue by jaeitee** [Pr20100/SOVOL-SV-06-Klipper-profile#1]
Unable to restart firmware.

> Option 'control' in section 'heater_bed' must be specified

> Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

**Comment by asdfmonster261** [comment]
I'm getting the same error


edit: 
I've gotten past the errors by putting this in the extruder and heater_bed sections

control: pid
pid_Kp: 
pid_Ki: 
pid_Kd: 

I had already run a PID autotune and had the values saved somewhere.

**Comment by Pr20100** [comment]
Thank you, these values are added and an update is coming ;)
