### ISSUE TITLE
MCU Serial value from the guide didn't work for me

### ISSUE THREAD

**Issue by willobar** [Pr20100/SOVOL-SV-06-Klipper-profile#12]
The Serial value in your readme is /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0, but I had to change that value to /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0 to establish the connection from my Pi to the printer. 

I'm not sure if it is because I have an older Pi, but you may want to consider updating the readme to include instructions for running "ls /dev/serial/by-id/*" to get the correct value.

**Comment by Pr20100** [comment]
Hello, it's not a step in my readme but a part of the linked official installation guide.
