### ISSUE TITLE
`GANTRY_CALIBRATION` leaves print head in dangerous position

### ISSUE THREAD

**Issue by wingertge** [Pr20100/SOVOL-SV-06-Klipper-profile#15]
Using the `GANTRY_CALIBRATION` macro parks the head in a spot where the Z probe doesn't have any bed under it, meaning any subsequent commands that use `G28 Z` (like the mesh level macro) will forcefully crash the print head into the bed because the Z probe never triggers.

Parking it in a spot where the probe is still over the bed might be a good idea.

**Comment by Pr20100** [comment]
After the gantry macro align at top she already make a G28z and stay on the middle of the bed so I don't understand your problem...
