### ISSUE TITLE
Add gcode M900 replacement as macro to enhance Pressure Advance calibration to be able to use the new method

### ISSUE THREAD

**Issue by MPC561** [Pr20100/SOVOL-SV-06-Klipper-profile#4]
Hi Pierre,
There is a new method to calibrate Pressure Advance with a pattern and no more with a cube. The new method is much more fast then printing a cube and need less material. In principle it can be done within 5-10 Minutes with below 1g of material.

Here the method is described: [[Click Me](https://teachingtechyt.github.io/calibration.html#linadv)]
For this pattern a Pattern Generator is available:[Click Me]( https://marlinfw.org/tools/lin_advance/k-factor.html)

The pattern generator uses the M900 code command to change the Pressure Advance K factor within the print. As M900 is not supported we should introduce a macro which translates the M900 to clipper syntax.

I have found a working (tested by me) macro from following GitHub repo: [Klick Me](https://github.com/Desuuuu/klipper-macros/tree/master/macros)

```
[gcode_macro M900]
gcode:
  {% if 'K' in params %}
    {% if 'E' in params %}
      SET_PRESSURE_ADVANCE EXTRUDER={params.E} ADVANCE={params.K}
    {% else %}
      SET_PRESSURE_ADVANCE ADVANCE={params.K}
    {% endif %}
  {% endif %}
```

I will add also another macro request in another Issue which is also used with the pattern generator but has also other very positive aspects (M204)

**Comment by Pr20100** [comment]
This method doesn't need any additions and works well for PA testing : https://ellis3dp.com/Pressure_Linear_Advance_Tool/
