### ISSUE TITLE
Issues with Multi Klipper

### ISSUE THREAD

**Issue by Twitch0815** [Pr20100/SOVOL-SV-06-Klipper-profile#7]
I am using multiple instances of Klipper which organizes different printers as  printer_1_data, printer_2_data, etc etc for how many instances you have

With the first version of files printer.cfg and printer profiles were the only paths that had to be adjusted

but with these updates I tried and cannot seem to find all the paths or ways to adjust the paths to get this to work.  

Can you make this friendly for multiple printer installs

think part of the problem is around
 /home/pi/klipper_config/config/ = /home/pi/printer_1_data/config/config/ (edited)

eg, /home/pi/klipper_config/config/options.cfg = /home/pi/printer_1_data/config/config/options.cfg

**Comment by Pr20100** [comment]
Hello, it's not possible to make it work in this way. For you it's maybe printer_1, for someone else will be printer_3... I've also already shortened the syntax path for the files, ex : 
NOW [include /config/drivers/TMC_2209.cfg]
BEFORE [/home/pi/printer_data/config/config/drivers/TMC_2209.cfg]
It's not possible for the printing-profiles files.
So if your're using the last update, you will have to try to change only the 3 files path in the "config/printing-profiles/ X-file" (2 lines for each) it should work. Can you make me a feedback?

**Comment by Twitch0815** [comment]
Sure I can try,  and give feedback 
Need to figure out what machine Gcode to change my cura as I was using marlin a long time not sure how to edit the gcode for klipper specifically.

Also is there a way to set z offset with the screen at the printer?

**Comment by Pr20100** [comment]
I have 2 things to do and this is it!
Will update the display cfg to add all the macros in a menu
Will make a file to give the start/end print gcode for the slicers (Prusa/Superslicer/Cura) cause there's some differences for each

**Comment by Twitch0815** [comment]
question,
with the newest release there is a firmware.bin file.  If we have already updated or kipper firmware on the printer do we need to reflash this, or is that unneeded? 
https://github.com/Pr20100/SOVOL-SV06-Klipper-profile/releases/tag/v120123

**Comment by Twitch0815** [comment]
Thus far the new file release setup is a lot easier to understand and the pathing.  Updating files didn't break connection to the printer.  I am also able to easily update the path information.  
Only thing is now I have a printer.cfg in both /home/pi/printer_2_data/ and /home/pi/printer_2_data/config  
The  authoritative one is  /home/pi/printer_2_data/ and /home/pi/printer_2_data/config/printer.cfg

For the PID tuning macro can you add one for PetG and ABS as well? Or is that superfluous.

Only thing I need now is the machine code for slicers and should be good to go.

**Comment by Twitch0815** [comment]
Alright I am still getting an error message though I have edited  all files in printer_profiles and printer.cfg


Error I am getting is 
GCode path received from Klipper does not match expected location.

Received: '/home/pie/printer_2_data/gcodes'
Expected: '/home/pi/printer_2_data/gcodes'

Modify the [virtual_sdcard] section Klipper's configuration to correct this error.

[virtual_sdcard]
path: /home/pi/printer_2_data/gcodes





This tech article seems to have a kind of fix
https://www.reddit.com/r/klippers/comments/nsj881/unable_to_upload_gcode_file_within_mainsail/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

but when I go to the moonraker directory and run data path fix its all configured for other directories and there are so many alias's cant figure out what to fix. 


This is causing bad functionality because when I upload a gcode file.  It shows up in Mainsail.
It shows up in my /home/pi/printer_2_data/gcodes directory
but it displays to console error unable to open file

then in my klipper logs it shows 
virtual_sdcard file open
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/extras/virtual_sdcard.py", line 178, in _load_file
    fname = files_by_lower[fname.lower()]
KeyError: 'ss_3dbenchy.gcode'
Unable to open file

**Comment by Pr20100** [comment]
- No need to reflash the printer.
- For future updates you could just copy and paste the files or lines you want to add. No need to change everything.
- So it's a synthax error : 
"Error I am getting is
GCode path received from Klipper does not match expected location.
Received: '/home/pie/printer_2_data/gcodes'
Expected: '/home/pi/printer_2_data/gcodes'"
- You should not run the data path fix, it's not made for that
- My readme file says : 
- > Be sure you have in mainsail.cfg :
     [virtual_sdcard]
     path: /home/pi/printer_data/gcodes
So you have to modify that to fit with your config
