### ISSUE TITLE
'DET' filament runout sensor pins support in SV06 klipper firmware?

### ISSUE THREAD

**Issue by xanderphillips** [Pr20100/SOVOL-SV-06-Klipper-profile#9]
I'm probably doing something wrong, as I am new to all this.

I believe the DET pin header on the mainboard can be used for a filament runout sensor.
From the SOVOL Marlin firmware repo for the SV06 it appears to me that the runout sensor should be PA4.

Do I need to edit a config file to enable those pins before I compile a new klipper bin firmware to have those pins exposed?

Sorry if I'm making a huge conceptual error.

**Comment by MPC561** [comment]
"Do I need to edit a config file to enable those pins before I compile a new klipper bin firmware to have those pins exposed?"

No. Klipper is compiled/flashed one time based on the configuration of your processor type and the interface between Mainboard and Stepper. All the other stuff is then configuration only and the firmware need no more to be touched.

This here is not a lesson book for beginners. Please inform yourself in the www. This is for Issues (New feature requests/failures) for the SV06 Klipper configuration.
